name: Kernel

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
  GSI:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with: 
          swap-size-gb: 12
        
      - name: start
        run: |
         pwd && ./S; ./C; ./P
        
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
         files: | 
          workspace/out/arch/arm64/boot/Image.gz-dtb
          name: Hatsune-${{ github.run_id }}
         tag_name: ${{ github.run_id }}
         body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: *.gz-dtb
          env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
